---
title: "How to use SQL language in R"
output: html_notebook
---
   
    SQL language is popular in structral data query.How to use sql achieve the same function in R ,in this article you will learn the function use SQL to achieve Data ETL,Extract,Transform,Load.

##Head function 
```{r}
library(sqldf)
library(RPostgreSQL)
library(DT)
options(sqldf.driver="SQLite")
options(gsunfn.engine="R")
sqldf()
# head
a1r <- head(warpbreaks)
a1s <- sqldf("select * from warpbreaks limit 6")
datatable(a1s)
identical(a1r, a1s)

```


##Subset function  
```{r}
a2r <- subset(CO2, grepl("^Qn", Plant))
a2s <- sqldf("select * from CO2 where Plant like 'Qn%'")
all.equal(as.data.frame(a2r), a2s)

data(farms, package = "MASS")
a3r <- subset(farms, Manag %in% c("BF", "HF"))
a3s <- sqldf("select * from farms where Manag in ('BF', 'HF')")
row.names(a3r) <- NULL
identical(a3r, a3s)

a4r <- subset(warpbreaks, breaks >= 20 & breaks <= 30)
a4s <- sqldf("select * from warpbreaks where breaks between 20 and 30", 
   row.names = TRUE)
identical(a4r, a4s)

a5r <- subset(farms, Mois == 'M1')
a5s <- sqldf("select * from farms where Mois = 'M1'", row.names = TRUE)
identical(a5r, a5s)

a6r <- subset(farms, Mois == 'M2')
a6s <- sqldf("select * from farms where Mois = 'M2'", row.names = TRUE)
identical(a6r, a6s)

```



##Rbind and join function 
```{r}
a7r <- rbind(a5r, a6r)
a7s <- sqldf("select * from a5s union all select * from a6s")
datatable(a7r)
row.names(a7r) <- NULL
```

##Aggregate function 

```{r }
# aggregate - avg conc and uptake by Plant and Type
a8r <- aggregate(iris[1:2], iris[5], mean)
a8s <- sqldf('select Species, avg("Sepal.Length") `Sepal.Length`, 
   avg("Sepal.Width") `Sepal.Width` from iris group by Species')
datatable(a8r)

```

## Do.call function  

```{r}
# by - avg conc and total uptake by Plant and Type
a9r <- do.call(rbind, by(iris, iris[5], function(x) with(x,
	data.frame(Species = Species[1], 
		mean.Sepal.Length = mean(Sepal.Length),
		mean.Sepal.Width = mean(Sepal.Width),
		mean.Sepal.ratio = mean(Sepal.Length/Sepal.Width)))))
row.names(a9r) <- NULL
a9s <- sqldf('select Species, avg("Sepal.Length") `mean.Sepal.Length`,
	avg("Sepal.Width") `mean.Sepal.Width`, 
	avg("Sepal.Length"/"Sepal.Width") `mean.Sepal.ratio` from iris
	group by Species')
datatable(a9r)
```



##Partition by function 
```{r }

tmp <- sqldf('select 
         "Species", 
       "Sepal.Length", 
       "Sepal.Length" - avg("Sepal.Length") over (partition by "Species") "above.mean"  from iris')

sqldf('select "Species", avg("Sepal.Length") 
       from tmp         
      where "above.mean" > 0 
      group by "Species"')
```


    sqldf package is a goog packages in R.
  
  

