---
title: "金融行为学热门羊群战术研究"
author: "Quandl WU LIXIN "
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r encho=FALSE, message=FALSE,warning=FALSE}
#plot packages
library(tvthemes)
library(dygraphs)
library(ggplot2)
library(plotly)
library(highcharter)
library(ggvis)
library(ggmap)
#other packages
library(lubridate)
library(dplyr)
library(forcats)
library(MAPA)
library(magick)
library(nnfor)
library(data.table)
library(quantmod)
library(PerformanceAnalytics)
library(TTR)
library(nnfor)
library(forecast)
library(xts)
library(zoo)
library(PortfolioAnalytics)
library(Quandl)
library(astsa)
library(flexdashboard)
library(dplyr)
#finance packages 
library(readr)
library(devtools)
library(foreach)
library(Tushare)
library(lubridate)
library(stringi)
library(stringr)

pro <-pro_api(token ='fe8102bf83f5f83f6608aa46fa5e985c534c227786236a1192e5fd55')

stocks_names<-pro(api_name = 'stock_basic')

latest_week<-Sys.Date()-days(15)
latest_day<-Sys.Date()-days(1)
latest_week<-Sys.Date()-days(15)
latest_month<-Sys.Date()-days(30)
start_date<-Sys.Date()-days(552)
get_data<-function(ts_code){
  start_date=start_date
  data<-pro(api_name = 'daily', ts_code=ts_code, start_date=start_date)
}
##get basket stocks 
get_stock_prices <- function(ticker, return_format = "tibble", ...) {
  # Get stock prices
  stock_prices <- get_data(ts_code= ticker, ...)
  colnames(stock_prices)<-c("ts_code","Date","open","high","low","close","pre_close","change","pct_change","volume","amount")
  Date_new<-stock_prices$Date
  stock_prices_xts<-as.xts(OHLCV(stock_prices),order.by=ymd(stock_prices$Date))
  # Rename
  names(stock_prices_xts) <- c("Open", "High", "Low", "Close","Adjusted","Volume")
  # Return in xts format if tibble is not specified
  if (return_format == "tibble") {
    stock_prices <- stock_prices_xts %>%
      as_tibble() %>%
      mutate(Date=ymd(Date_new))
  } else {
    stock_prices <- stock_prices_xts
  }
  stock_prices
}

##获取股票的反弹数据
get_log_returns<-function(data){
   data%>%
    mutate(Log.Returns=dailyReturn(as.xts(as.numeric(Close),order.by=Date),subset=NULL,type='arithmetic',leading=TRUE))%>%
    select(Date,Log.Returns)%>%
    as_tibble() }

```


* 投资也，家庭之大事，死生之地，存亡之道，比现代战争更加残酷，唯有一点就是时间站在普通投资者这边，时间站在弱小力量这方，唯有发力发扬司马懿忍者精神才能成功！投资有风险，投资需要谨慎，投资需要多交流！



## 行业/板块大势


```{r encho=FALSE, message=FALSE,warning=FALSE}
pro_api<-function (token) {
  http_url <- "http://api.Tushare.pro"
  return(function(api_name, ...) {
    params <- list(token = token, api_name = api_name, params = list(...))
    r <- httr::POST(http_url, body = params, encode = "json")
    res <- httr::content(r, "parsed", "application/json")
    if (is.null(res$data)) {
      return(NULL)
    }
    columns <- res$data$fields
    items <- res$data$items
    df <- as.data.frame(data.table::rbindlist(items))
    colnames(df) <- columns
    return(df)
  }) }


#dataprices = pro(api_name="daily",trade_date='20221027')
today<-str_remove(str_remove(Sys.Date(), "-"),"-")
dataprices = pro(api_name="daily",trade_date=today)

df_all<-dataprices%>%left_join(stocks_names)%>%
  filter(industry=="出版")
#filter(pct_chg > 8 & pct_chg < 21)

df_all$list_date<-ymd(df_all$list_date)
latest_month<-Sys.Date()-days(350)

###插入一个表格
library(flexpivot)
library(flextable)
df_all %>%
  select(industry,market)%>%
  subset(industry %in% c("出版")) %>%
  pivot_table("industry", "market") %>%
  pivot_format()
##
stocks_name<-stocks_names%>%filter(name %in% df_all$name & ymd('20230201')>ymd(list_date))
#stocks_name<-stocks_names%>%
#  filter(name %in% c())
library(purrr)
library(dplyr)
library(tidyverse)
china_stocks <- stocks_name %>%
  mutate(
    stock.prices = map(ts_code, 
                       function(.x) get_stock_prices(.x)
    ),
    log.returns  = map(stock.prices, 
                       function(.x) get_log_returns(.x)),
    mean.log.returns = map_dbl(log.returns, ~ mean(.$Log.Returns)),
    sd.log.returns   = map_dbl(log.returns, ~ sd(.$Log.Returns)),
    n.trade.days = map_dbl(stock.prices, nrow)
  )%>%as_tibble()

```



## 分布全景视图

```{r echo=FALSE,warning=FALSE,message=FALSE}
library(tvthemes)
library(lubridate)
library(forcats) 
library(proto)
library(ggmap)
library(DT)
library(highcharter)
library(viridisLite)
library(treemap)
library(flexdashboard)
library(RJSONIO)
treemap_data <- china_stocks%>%
  unnest(stock.prices)%>%
  mutate(category = gsub(" ", "-", industry),
         subcategory = gsub(" ", "-", market),
         ratio=mean.log.returns/sd.log.returns,
         Volume=as.numeric(mean.log.returns)) %>%
  select(category, subcategory,name,Volume,ratio)%>%
  sample_n(100)

hchart(
  data_to_hierarchical(treemap_data,c("category","subcategory","name"),    size=Volume, colors =rev(viridis(6))),type = "treemap",allowDrillToNode = TRUE,tooltip = list(valueDecimals = FALSE)) %>% 
  hc_chart(
    style = list(fontFamily = "Gloria Hallelujah")) %>% 
  hc_title(text = "上市公司行业分布",
           style = list(fontFamily = "Gloria Hallelujah")) %>% 
  hc_size(height = 800,width = 1000)
```



##  投资回报排名

```{r echo=FALSE,warning=FALSE,message=FALSE}
stocklist <- china_stocks %>%
  filter(n.trade.days >= 10) %>%
  mutate(reward.metric = 2500 * (mean.log.returns / sd.log.returns))

top_n_limit <- 30

hp <- stocklist %>%
  mutate(rank = reward.metric %>% desc() %>% min_rank()) %>%
  filter(rank <= top_n_limit) %>%
  arrange(rank)
#table
hp %>%
  select(name, rank, reward.metric)%>%
  datatable()

# Data Prep
rownames(hp)<-hp$name  # create new column for car names
hp$return_type <- ifelse(hp$reward.metric< 100, "below", "above") 
hp<- hp[order(hp$reward.metric), ]   
# Diverging Barcharts

hchart(hp,hcaes(x=name,y=reward.metric,label=return_type),type="column")%>%
   hc_yAxis(title = list(text = "投资回报率"),
           labels = list(format = "{value}") ) %>% 
  hc_xAxis( categories = hp$name) %>%
  hc_plotOptions(series = list(
    boderWidth = 0,
    dataLabels = list(enabled = TRUE)))%>%
  hc_title(text="个股投资回报排名",style = list(fontFamily = "Gloria Hallelujah"))%>%
  hc_subtitle(text="离群值与行业龙头")%>%
  hc_caption(text='投资回报仅仅代表过去收益情况，不代表未来')%>%
  hc_add_theme(hc_theme_superheroes())%>%
  hc_size(height = 800,width=1000)

```

 
##  投资风险均衡

```{r echo=FALSE,warning=FALSE,message=FALSE}
library(ggrepel)
library(dplyr)
library(tidyr)
library(tidyverse)

hchart(stocklist,hcaes(x= sd.log.returns, y=reward.metric,group=name,col=name,size= sd.log.returns),type="scatter")%>%
  hc_plotOptions(series = list(
    boderWidth = 0,
    dataLabels = list(enabled = TRUE)))%>%
  hc_title(text="风险VS回报均衡",style = list(fontFamily = "Gloria Hallelujah"))%>%
  hc_caption(text='投资有风险，投资需要谨慎，咨询LIXIN WU')%>%
  hc_add_theme(hc_theme_sandsignika())%>%
  hc_size(height = 800,width=1000)


```


##  皮尔逊相关系数

```{r echo=FALSE,warning=FALSE,message=FALSE}

library(ggplot2)
library(ggcorrplot)

ts_codes<-stocks_name$ts_code

prices = Map(function(n)
{
   #print(n)
  tryCatch(get_data(n)[,6], error = function(e) NA)
}, ts_codes)
N = length(prices)
# identify symbols returning valid data
i = ! unlist(Map(function(i) is.na(prices[i]), seq(N)))
# combine returned prices list into a matrix, one column for each symbol with valid data
prices = Reduce(cbind, prices[i])
colnames(prices) = stocks_name$name[i]
##########clean up and transform data 
for(j in 1:ncol(prices)) prices[, j] = na.locf(prices[, j])       # fill in
prices = prices[, apply(prices, 2, function(x) ! any(is.na(x)))]

log_returns = apply(prices, 2, function(x) diff(log(x)))

X = cor(log_returns)
colnames(X)<-stocks_name$name[i]
corr <- round(cor(log_returns), 1)
library(corrplot)
as.data.frame(corr[1:10,1:11])%>% 
  flextable() %>% 
  colformat_double() %>% autofit() %>% 
  align(align = "center", part = "all") %>% 
  bg(bg = "black", part = "header") %>% 
  color(color = "white", part = "all") %>% 
  bg(bg = scales::col_numeric(palette = "viridis", domain = c(0, 1)))

# Plot
#corrplot.mixed(corr, lower = 'shade', upper = 'pie', order = #'hclust')

```



##  社交关系网分析

```{r echo=FALSE,warning=FALSE,message=FALSE}
 
L = eigen(X, symmetric=TRUE)
#plot(L$values, ylab="eigenvalues")
#abline(v=10)

N = 10  # (use 1st 10 eigenvectors, set N larger to reduce regularization)
P = L$vectors[, 1:N] %*% ((1 / L$values[1:N]) * t(L$vectors[, 1:N]))
P = P / tcrossprod(sqrt(diag(P)))

library(corpcor)
library(igraph)

threshold = 0.92

Q = P * (P > quantile(P, probs=threshold))  

# thresholded precision matrix
g = graph.adjacency(Q, mode="undirected", weighted=TRUE, diag=FALSE) # ...expressed as a graph

# The rest of the code lumps any singletons lacking edges into a single 'unassociated' group shown in gray
# (also assigning distinct colors to the other groups).
#聚类分析
x = groups(cluster_louvain(g))

i = unlist(lapply(x, length))

d = order(i, decreasing=TRUE)
x = x[d]
i = i[d]
j = i > 1
s = sum(j)
names(x)[j] = seq(1, s)
names(x)[! j] = s + 1 
grp = as.integer(rep(names(x), i))
clrs = c(rainbow(s), "gray")[grp[order(unlist(x))]]
g = set_vertex_attr(g, "color", value=clrs)

library(threejs)
graphjs(g, vertex.size=0.2, vertex.shape=colnames(X), edge.alpha=0.5)
```



## 股票聚类分析

```{r echo=FALSE,warning=FALSE,message=FALSE,fig.cap="股票聚类分析图"}
library(corrplot)
library(gplots)
library(RColorBrewer)
library(heatmaply)
library(d3heatmap)
heatmapdata<-china_stocks%>%
  unnest(stock.prices)%>%
  select(Date,name,Close)%>%
  mutate(Close=as.numeric(Close))%>%
  spread(key=name, value=Close)%>%
  select(-Date)


d3heatmap(heatmapdata,scale = "column", 
          show_grid = TRUE, anim_duration = 500,
          distfun = dist, hclustfun = hclust,height = 800,width=1000)

```


```{r echo=FALSE,warning=FALSE,message=FALSE,fig.cap="股票聚类分析图"}
library(magick)
img<-image_read("//Users//wulixin//Desktop//kehu.png")
img
```


 执业编号：S0770621060006 投资有风险，投资需要谨慎

更多内容点击 [QuandlFinance](http://wulixin.github.io//QuandlFinance//home.html) 
footnotes^[内心的强大才是真的强大]